apiVersion: v1
kind: Pod
metadata:
  name: datamaster-pod
  labels:
    app: datamaster
spec:
  containers:
      - name: data-master
        image: alincorodescu/msc-workflows-data-master:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: ASPNETCORE_URLS
            value: http://+:9377
          - name: NODE_IP
            valueFrom:
              fieldRef: 
                fieldPath: status.hostIP
        ports:
        # For GRPC calls
          - containerPort: 9377
            protocol: TCP
        # For REST calls
          - containerPort: 10001
            protocol: TCP
