apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: storage-adapter
spec:
  selector:
    matchLabels:
      name: storage-adapter
  template:
    metadata:
      labels:
        name: storage-adapter
        zone: zone1
        region: region1
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: storage-adapter
        image: storage-adapter:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 1000m
            memory: 500Mi
        volumeMounts:
        - name: store
          mountPath: /store
        ports:
          - containerPort: 5001
            hostPort: 5001
        env:
          - name: ASPNETCORE_URLS
            value: http://+:5001
          - name: NODE_IP
            valueFrom:
              fieldRef: 
                fieldPath: status.hostIP
          - name: LOCALIZATION_HOST
            valueFrom:
              fieldRef: 
                fieldPath: status.hostIP
          - name: LOCALIZATION_ZONE
            valueFrom:
              fieldRef: 
                fieldPath: metadata.labels['zone']
          - name: LOCALIZATION_REGION
            valueFrom:
              fieldRef: 
                fieldPath: metadata.labels['region']
          
      volumes:
      - name: store
        hostPath:
          path: /store
