apiVersion: v1
kind: Pod
metadata:
  name: datamaster-pod
  labels:
    app: datamaster
spec:
  containers:
      - name: data-master
        image: data-master:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: ASPNETCORE_URLS
            value: http://+:9377
        ports:
          - containerPort: 9377
            protocol: TCP
