apiVersion: v1
kind: Pod
metadata:
  name: step-pod
  labels:
    stepName: step1
spec:
  containers:
      - name: sidecar
        image: sidecar:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: ASPNETCORE_URLS
            value: http://+:5000
        ports:
          - containerPort: 5000
            protocol: TCP
      - name: compute
        image: compute:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: ASPNETCORE_URLS
            value: http://localhost:5002
        volumeMounts:
          - mountPath: /in
            name: inputs
          - mountPath: /out
            name: outputs
  volumes:
      - name: inputs
        hostPath:
          path: /store/inputs
      
      - name: outputs
        hostPath:
          path: /store/outputs

