apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataplane
spec:
  selector:
    matchLabels:
      app: dataplane
  template:
    metadata:
      labels:
        app: dataplane
    spec:
      containers:
      - name: dataplane
        image: data_plane:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000