apiVersion: v1
kind: Pod
metadata:
  name: shell-demo-2
spec:
  volumes:
  - name: test-volume
    hostPath:
      path: /home/alin/sandbox/test/lntest
      type: Directory
  containers:
      - name: busybox
        image: busybox:latest
        stdin: true
        stdinOnce: true
        tty: true
        command: [ "sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /lntest
            name: test-volume
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef : 
                fieldPath : status.hostIP